### ISSUE TITLE
Jupyter Notebook

### ISSUE THREAD

**Issue by stevenveenma** [MA-MacDonald/stream_engine#1]
A very useful addition to matplotlib. Unfortunately I can't get this running on Jupyter notebook using %matplotlib inline or  rc('animation', html='html5'). Are there any more tricks? 

I am thinking of calculating a regression function based on streaming data. Is it possible to plot this in the same graph as the data?

**Comment by MA-MacDonald** [comment]
Hey @stevenveenma , you can use '%matplotlib notebook' instead of '%matplotlib inline'. You can also plot anything you like in the same graph as the data. If you give me an example of what you are trying to do I can show you how to do it.
